pages = [{"l":"index.html#","e":false,"i":"","n":"root","t":"root","d":"","k":"static","x":""},
{"l":"io/github/srs.html#","e":false,"i":"","n":"io.github.srs","t":"io.github.srs","d":"","k":"package","x":""},
{"l":"io/github/srs/controller.html#","e":false,"i":"","n":"io.github.srs.controller","t":"io.github.srs.controller","d":"","k":"package","x":""},
{"l":"io/github/srs/controller/ControllerModule$.html#","e":false,"i":"","n":"ControllerModule","t":"ControllerModule","d":"io.github.srs.controller","k":"object","x":""},
{"l":"io/github/srs/controller/ControllerModule$.html#Requirements-0","e":false,"i":"","n":"Requirements","t":"Requirements = Provider & Provider","d":"io.github.srs.controller.ControllerModule","k":"type","x":""},
{"l":"io/github/srs/controller/ControllerModule$$Component.html#","e":false,"i":"","n":"Component","t":"Component","d":"io.github.srs.controller.ControllerModule","k":"trait","x":""},
{"l":"io/github/srs/controller/ControllerModule$$Component$Controller$.html#","e":false,"i":"","n":"Controller","t":"Controller","d":"io.github.srs.controller.ControllerModule.Component","k":"object","x":""},
{"l":"io/github/srs/controller/ControllerModule$$Component$Controller$.html#apply-fffff463","e":false,"i":"","n":"apply","t":"apply(): Controller","d":"io.github.srs.controller.ControllerModule.Component.Controller","k":"def","x":""},
{"l":"io/github/srs/controller/ControllerModule$$Controller.html#","e":false,"i":"","n":"Controller","t":"Controller","d":"io.github.srs.controller.ControllerModule","k":"trait","x":""},
{"l":"io/github/srs/controller/ControllerModule$$Controller.html#plotData-94c","e":false,"i":"","n":"plotData","t":"plotData(): Unit","d":"io.github.srs.controller.ControllerModule.Controller","k":"def","x":""},
{"l":"io/github/srs/controller/ControllerModule$$Controller.html#start-94c","e":false,"i":"","n":"start","t":"start(): Unit","d":"io.github.srs.controller.ControllerModule.Controller","k":"def","x":""},
{"l":"io/github/srs/controller/ControllerModule$$Interface.html#","e":false,"i":"","n":"Interface","t":"Interface extends Provider, Component","d":"io.github.srs.controller.ControllerModule","k":"trait","x":""},
{"l":"io/github/srs/controller/ControllerModule$$Provider.html#","e":false,"i":"","n":"Provider","t":"Provider","d":"io.github.srs.controller.ControllerModule","k":"trait","x":""},
{"l":"io/github/srs/controller/ControllerModule$$Provider.html#controller-0","e":false,"i":"","n":"controller","t":"controller: Controller","d":"io.github.srs.controller.ControllerModule.Provider","k":"val","x":""},
{"l":"io/github/srs/model.html#","e":false,"i":"","n":"io.github.srs.model","t":"io.github.srs.model","d":"","k":"package","x":""},
{"l":"io/github/srs/model/ModelModule$.html#","e":false,"i":"","n":"ModelModule","t":"ModelModule","d":"io.github.srs.model","k":"object","x":""},
{"l":"io/github/srs/model/ModelModule$$Component.html#","e":false,"i":"","n":"Component","t":"Component","d":"io.github.srs.model.ModelModule","k":"trait","x":""},
{"l":"io/github/srs/model/ModelModule$$Component$Model$.html#","e":false,"i":"","n":"Model","t":"Model","d":"io.github.srs.model.ModelModule.Component","k":"object","x":""},
{"l":"io/github/srs/model/ModelModule$$Component$Model$.html#apply-34c","e":false,"i":"","n":"apply","t":"apply(): Model","d":"io.github.srs.model.ModelModule.Component.Model","k":"def","x":""},
{"l":"io/github/srs/model/ModelModule$$Interface.html#","e":false,"i":"","n":"Interface","t":"Interface extends Provider, Component","d":"io.github.srs.model.ModelModule","k":"trait","x":""},
{"l":"io/github/srs/model/ModelModule$$Model.html#","e":false,"i":"","n":"Model","t":"Model","d":"io.github.srs.model.ModelModule","k":"trait","x":""},
{"l":"io/github/srs/model/ModelModule$$Model.html#getData-0","e":false,"i":"","n":"getData","t":"getData: Int","d":"io.github.srs.model.ModelModule.Model","k":"def","x":""},
{"l":"io/github/srs/model/ModelModule$$Provider.html#","e":false,"i":"","n":"Provider","t":"Provider","d":"io.github.srs.model.ModelModule","k":"trait","x":""},
{"l":"io/github/srs/model/ModelModule$$Provider.html#model-0","e":false,"i":"","n":"model","t":"model: Model","d":"io.github.srs.model.ModelModule.Provider","k":"val","x":""},
{"l":"io/github/srs/view.html#","e":false,"i":"","n":"io.github.srs.view","t":"io.github.srs.view","d":"","k":"package","x":""},
{"l":"io/github/srs/view/SimpleView.html#","e":false,"i":"","n":"SimpleView","t":"SimpleView","d":"io.github.srs.view","k":"class","x":""},
{"l":"io/github/srs/view/SimpleView.html#close-94c","e":false,"i":"","n":"close","t":"close(): Unit","d":"io.github.srs.view.SimpleView","k":"def","x":""},
{"l":"io/github/srs/view/SimpleView.html#init-94c","e":false,"i":"","n":"init","t":"init(): Unit","d":"io.github.srs.view.SimpleView","k":"def","x":""},
{"l":"io/github/srs/view/SimpleView.html#plotData-fffff3b3","e":false,"i":"","n":"plotData","t":"plotData(data: Int): Unit","d":"io.github.srs.view.SimpleView","k":"def","x":""},
{"l":"io/github/srs/view/ViewModule$.html#","e":false,"i":"","n":"ViewModule","t":"ViewModule","d":"io.github.srs.view","k":"object","x":""},
{"l":"io/github/srs/view/ViewModule$.html#Requirements-0","e":false,"i":"","n":"Requirements","t":"Requirements = Provider","d":"io.github.srs.view.ViewModule","k":"type","x":""},
{"l":"io/github/srs/view/ViewModule$$Component.html#","e":false,"i":"","n":"Component","t":"Component","d":"io.github.srs.view.ViewModule","k":"trait","x":""},
{"l":"io/github/srs/view/ViewModule$$Component$View$.html#","e":false,"i":"","n":"View","t":"View","d":"io.github.srs.view.ViewModule.Component","k":"object","x":""},
{"l":"io/github/srs/view/ViewModule$$Component$View$.html#apply-fffff44c","e":false,"i":"","n":"apply","t":"apply(): View","d":"io.github.srs.view.ViewModule.Component.View","k":"def","x":""},
{"l":"io/github/srs/view/ViewModule$$Interface.html#","e":false,"i":"","n":"Interface","t":"Interface extends Provider, Component","d":"io.github.srs.view.ViewModule","k":"trait","x":""},
{"l":"io/github/srs/view/ViewModule$$Provider.html#","e":false,"i":"","n":"Provider","t":"Provider","d":"io.github.srs.view.ViewModule","k":"trait","x":""},
{"l":"io/github/srs/view/ViewModule$$Provider.html#view-0","e":false,"i":"","n":"view","t":"view: View","d":"io.github.srs.view.ViewModule.Provider","k":"val","x":""},
{"l":"io/github/srs/view/ViewModule$$View.html#","e":false,"i":"","n":"View","t":"View","d":"io.github.srs.view.ViewModule","k":"trait","x":""},
{"l":"io/github/srs/view/ViewModule$$View.html#init-94c","e":false,"i":"","n":"init","t":"init(): Unit","d":"io.github.srs.view.ViewModule.View","k":"def","x":""},
{"l":"io/github/srs/view/ViewModule$$View.html#plotData-fffff3b3","e":false,"i":"","n":"plotData","t":"plotData(data: Int): Unit","d":"io.github.srs.view.ViewModule.View","k":"def","x":""},
{"l":"io/github/srs/Launcher$.html#","e":false,"i":"","n":"Launcher","t":"Launcher extends Interface, Interface, Interface","d":"io.github.srs","k":"object","x":""},
{"l":"io/github/srs/Launcher$.html#controller-0","e":false,"i":"","n":"controller","t":"controller: Controller","d":"io.github.srs.Launcher","k":"val","x":""},
{"l":"io/github/srs/Launcher$.html#model-0","e":false,"i":"","n":"model","t":"model: Model","d":"io.github.srs.Launcher","k":"val","x":""},
{"l":"io/github/srs/Launcher$.html#run-94c","e":false,"i":"","n":"run","t":"run(): Unit","d":"io.github.srs.Launcher","k":"def","x":""},
{"l":"io/github/srs/Launcher$.html#view-0","e":false,"i":"","n":"view","t":"view: View","d":"io.github.srs.Launcher","k":"val","x":""},
{"l":"io/github/srs/run.html#","e":false,"i":"","n":"run","t":"run","d":"io.github.srs","k":"class","x":""}];