pages = [{"l":"index.html#","e":false,"i":"","n":"root","t":"root","d":"","k":"static","x":""},
{"l":"io/github/srs.html#","e":false,"i":"","n":"io.github.srs","t":"io.github.srs","d":"","k":"package","x":""},
{"l":"io/github/srs/controller.html#","e":false,"i":"","n":"io.github.srs.controller","t":"io.github.srs.controller","d":"","k":"package","x":""},
{"l":"io/github/srs/controller/ControllerModule$.html#","e":false,"i":"","n":"ControllerModule","t":"ControllerModule","d":"io.github.srs.controller","k":"object","x":""},
{"l":"io/github/srs/controller/ControllerModule$.html#Requirements-0","e":false,"i":"","n":"Requirements","t":"Requirements = Provider & Provider","d":"io.github.srs.controller.ControllerModule","k":"type","x":""},
{"l":"io/github/srs/controller/ControllerModule$$Component.html#","e":false,"i":"","n":"Component","t":"Component","d":"io.github.srs.controller.ControllerModule","k":"trait","x":""},
{"l":"io/github/srs/controller/ControllerModule$$Component$Controller$.html#","e":false,"i":"","n":"Controller","t":"Controller","d":"io.github.srs.controller.ControllerModule.Component","k":"object","x":""},
{"l":"io/github/srs/controller/ControllerModule$$Component$Controller$.html#apply-fffff463","e":false,"i":"","n":"apply","t":"apply(): Controller","d":"io.github.srs.controller.ControllerModule.Component.Controller","k":"def","x":""},
{"l":"io/github/srs/controller/ControllerModule$$Controller.html#","e":false,"i":"","n":"Controller","t":"Controller","d":"io.github.srs.controller.ControllerModule","k":"trait","x":""},
{"l":"io/github/srs/controller/ControllerModule$$Controller.html#plotData-94c","e":false,"i":"","n":"plotData","t":"plotData(): Unit","d":"io.github.srs.controller.ControllerModule.Controller","k":"def","x":""},
{"l":"io/github/srs/controller/ControllerModule$$Controller.html#start-94c","e":false,"i":"","n":"start","t":"start(): Unit","d":"io.github.srs.controller.ControllerModule.Controller","k":"def","x":""},
{"l":"io/github/srs/controller/ControllerModule$$Interface.html#","e":false,"i":"","n":"Interface","t":"Interface extends Provider, Component","d":"io.github.srs.controller.ControllerModule","k":"trait","x":""},
{"l":"io/github/srs/controller/ControllerModule$$Provider.html#","e":false,"i":"","n":"Provider","t":"Provider","d":"io.github.srs.controller.ControllerModule","k":"trait","x":""},
{"l":"io/github/srs/controller/ControllerModule$$Provider.html#controller-0","e":false,"i":"","n":"controller","t":"controller: Controller","d":"io.github.srs.controller.ControllerModule.Provider","k":"val","x":""},
{"l":"io/github/srs/model.html#","e":false,"i":"","n":"io.github.srs.model","t":"io.github.srs.model","d":"","k":"package","x":""},
{"l":"io/github/srs/model.html#Point2D-0","e":false,"i":"","n":"Point2D","t":"Point2D = (Double, Double)","d":"io.github.srs.model","k":"type","x":""},
{"l":"io/github/srs/model.html#distanceTo-fffff6fd","e":false,"i":"extension (p: Point2D)","n":"distanceTo","t":"distanceTo(other: Point2D): Double","d":"io.github.srs.model","k":"def","x":""},
{"l":"io/github/srs/model/environment.html#","e":false,"i":"","n":"io.github.srs.model.environment","t":"io.github.srs.model.environment","d":"","k":"package","x":""},
{"l":"io/github/srs/model/environment/Environment.html#","e":false,"i":"","n":"Environment","t":"Environment","d":"io.github.srs.model.environment","k":"trait","x":""},
{"l":"io/github/srs/model/environment/Environment.html#entities-0","e":false,"i":"","n":"entities","t":"entities: Set[Entity]","d":"io.github.srs.model.environment.Environment","k":"val","x":""},
{"l":"io/github/srs/model/environment/Environment.html#height-0","e":false,"i":"","n":"height","t":"height: Double","d":"io.github.srs.model.environment.Environment","k":"val","x":""},
{"l":"io/github/srs/model/environment/Environment.html#width-0","e":false,"i":"","n":"width","t":"width: Double","d":"io.github.srs.model.environment.Environment","k":"val","x":""},
{"l":"io/github/srs/model/environment/Environment$.html#","e":false,"i":"","n":"Environment","t":"Environment","d":"io.github.srs.model.environment","k":"object","x":""},
{"l":"io/github/srs/model/environment/Environment$.html#apply-b49","e":false,"i":"","n":"apply","t":"apply(width: Double, height: Double, entities: Set[Entity]): Validation[Environment]","d":"io.github.srs.model.environment.Environment","k":"def","x":""},
{"l":"io/github/srs/model/environment/Environment$.html#unapply-fffff213","e":false,"i":"","n":"unapply","t":"unapply(env: Environment): Option[(Double, Double, Set[Entity])]","d":"io.github.srs.model.environment.Environment","k":"def","x":""},
{"l":"io/github/srs/model/validation.html#","e":false,"i":"","n":"io.github.srs.model.validation","t":"io.github.srs.model.validation","d":"","k":"package","x":""},
{"l":"io/github/srs/model/validation.html#Validation-0","e":false,"i":"","n":"Validation","t":"Validation[+A] = Either[DomainError, A]","d":"io.github.srs.model.validation","k":"type","x":""},
{"l":"io/github/srs/model/validation/DomainError.html#","e":false,"i":"","n":"DomainError","t":"DomainError","d":"io.github.srs.model.validation","k":"enum","x":""},
{"l":"io/github/srs/model/validation/DomainError$$NegativeOrZero.html#","e":false,"i":"","n":"NegativeOrZero","t":"NegativeOrZero(field: String, value: Double)","d":"io.github.srs.model.validation.DomainError","k":"class","x":""},
{"l":"io/github/srs/model/validation/DomainError$$NegativeOrZero.html#","e":false,"i":"","n":"NegativeOrZero","t":"NegativeOrZero(field: String, value: Double)","d":"io.github.srs.model.validation.DomainError","k":"class","x":""},
{"l":"io/github/srs/model/validation/Validation$.html#","e":false,"i":"","n":"Validation","t":"Validation","d":"io.github.srs.model.validation","k":"object","x":""},
{"l":"io/github/srs/model/validation/Validation$.html#positive-f11","e":false,"i":"","n":"positive","t":"positive[T](field: String, v: T)(using n: Numeric[T]): Validation[T]","d":"io.github.srs.model.validation.Validation","k":"def","x":""},
{"l":"io/github/srs/model/Entity.html#","e":false,"i":"","n":"Entity","t":"Entity","d":"io.github.srs.model","k":"trait","x":""},
{"l":"io/github/srs/model/Entity.html#orientation-0","e":false,"i":"","n":"orientation","t":"orientation: Orientation","d":"io.github.srs.model.Entity","k":"def","x":""},
{"l":"io/github/srs/model/Entity.html#position-0","e":false,"i":"","n":"position","t":"position: Point2D","d":"io.github.srs.model.Entity","k":"def","x":""},
{"l":"io/github/srs/model/Entity.html#shape-0","e":false,"i":"","n":"shape","t":"shape: ShapeType","d":"io.github.srs.model.Entity","k":"def","x":""},
{"l":"io/github/srs/model/ModelModule$.html#","e":false,"i":"","n":"ModelModule","t":"ModelModule","d":"io.github.srs.model","k":"object","x":""},
{"l":"io/github/srs/model/ModelModule$$Component.html#","e":false,"i":"","n":"Component","t":"Component","d":"io.github.srs.model.ModelModule","k":"trait","x":""},
{"l":"io/github/srs/model/ModelModule$$Component$Model$.html#","e":false,"i":"","n":"Model","t":"Model","d":"io.github.srs.model.ModelModule.Component","k":"object","x":""},
{"l":"io/github/srs/model/ModelModule$$Component$Model$.html#apply-34c","e":false,"i":"","n":"apply","t":"apply(): Model","d":"io.github.srs.model.ModelModule.Component.Model","k":"def","x":""},
{"l":"io/github/srs/model/ModelModule$$Interface.html#","e":false,"i":"","n":"Interface","t":"Interface extends Provider, Component","d":"io.github.srs.model.ModelModule","k":"trait","x":""},
{"l":"io/github/srs/model/ModelModule$$Model.html#","e":false,"i":"","n":"Model","t":"Model","d":"io.github.srs.model.ModelModule","k":"trait","x":""},
{"l":"io/github/srs/model/ModelModule$$Model.html#getData-0","e":false,"i":"","n":"getData","t":"getData: Int","d":"io.github.srs.model.ModelModule.Model","k":"def","x":""},
{"l":"io/github/srs/model/ModelModule$$Provider.html#","e":false,"i":"","n":"Provider","t":"Provider","d":"io.github.srs.model.ModelModule","k":"trait","x":""},
{"l":"io/github/srs/model/ModelModule$$Provider.html#model-0","e":false,"i":"","n":"model","t":"model: Model","d":"io.github.srs.model.ModelModule.Provider","k":"val","x":""},
{"l":"io/github/srs/model/Orientation.html#","e":false,"i":"","n":"Orientation","t":"Orientation","d":"io.github.srs.model","k":"trait","x":""},
{"l":"io/github/srs/model/Orientation.html#degrees-0","e":false,"i":"","n":"degrees","t":"degrees: Double","d":"io.github.srs.model.Orientation","k":"def","x":""},
{"l":"io/github/srs/model/Orientation.html#toRadians-0","e":false,"i":"","n":"toRadians","t":"toRadians: Double","d":"io.github.srs.model.Orientation","k":"def","x":""},
{"l":"io/github/srs/model/Orientation$.html#","e":false,"i":"","n":"Orientation","t":"Orientation","d":"io.github.srs.model","k":"object","x":""},
{"l":"io/github/srs/model/Orientation$.html#apply-c35","e":false,"i":"","n":"apply","t":"apply(degree: Double): Orientation","d":"io.github.srs.model.Orientation","k":"def","x":""},
{"l":"io/github/srs/model/Point2D$.html#","e":false,"i":"","n":"Point2D","t":"Point2D","d":"io.github.srs.model","k":"object","x":""},
{"l":"io/github/srs/model/Point2D$.html#apply-9e4","e":false,"i":"","n":"apply","t":"apply(x: Double, y: Double): Point2D","d":"io.github.srs.model.Point2D","k":"def","x":""},
{"l":"io/github/srs/model/ShapeType.html#","e":false,"i":"","n":"ShapeType","t":"ShapeType","d":"io.github.srs.model","k":"enum","x":""},
{"l":"io/github/srs/model/ShapeType$$Circle.html#","e":false,"i":"","n":"Circle","t":"Circle(radius: Double)","d":"io.github.srs.model.ShapeType","k":"class","x":""},
{"l":"io/github/srs/model/ShapeType$$Rectangle.html#","e":false,"i":"","n":"Rectangle","t":"Rectangle(width: Double, height: Double)","d":"io.github.srs.model.ShapeType","k":"class","x":""},
{"l":"io/github/srs/model/ShapeType$$Circle.html#","e":false,"i":"","n":"Circle","t":"Circle(radius: Double)","d":"io.github.srs.model.ShapeType","k":"class","x":""},
{"l":"io/github/srs/model/ShapeType$$Rectangle.html#","e":false,"i":"","n":"Rectangle","t":"Rectangle(width: Double, height: Double)","d":"io.github.srs.model.ShapeType","k":"class","x":""},
{"l":"io/github/srs/model/StaticEntity.html#","e":false,"i":"","n":"StaticEntity","t":"StaticEntity(val position: Point2D, val orientation: Orientation) extends Entity","d":"io.github.srs.model","k":"enum","x":""},
{"l":"io/github/srs/model/StaticEntity$$Obstacle.html#","e":false,"i":"","n":"Obstacle","t":"Obstacle(pos: Point2D, orient: Orientation, width: Double, height: Double) extends StaticEntity","d":"io.github.srs.model.StaticEntity","k":"class","x":""},
{"l":"io/github/srs/model/StaticEntity$$Light.html#","e":false,"i":"","n":"Light","t":"Light(pos: Point2D, orient: Orientation, radius: Double, intensity: Double, attenuation: Double) extends StaticEntity","d":"io.github.srs.model.StaticEntity","k":"class","x":""},
{"l":"io/github/srs/model/StaticEntity$$Obstacle.html#","e":false,"i":"","n":"Obstacle","t":"Obstacle(pos: Point2D, orient: Orientation, width: Double, height: Double) extends StaticEntity","d":"io.github.srs.model.StaticEntity","k":"class","x":""},
{"l":"io/github/srs/model/StaticEntity$$Light.html#","e":false,"i":"","n":"Light","t":"Light(pos: Point2D, orient: Orientation, radius: Double, intensity: Double, attenuation: Double) extends StaticEntity","d":"io.github.srs.model.StaticEntity","k":"class","x":""},
{"l":"io/github/srs/model/StaticEntity$.html#","e":false,"i":"","n":"StaticEntity","t":"StaticEntity","d":"io.github.srs.model","k":"object","x":""},
{"l":"io/github/srs/model/StaticEntity$.html#light-fffff8c2","e":false,"i":"","n":"light","t":"light(pos: Point2D, orient: Orientation, radius: Double, intensity: Double, attenuation: Double): Validation[StaticEntity]","d":"io.github.srs.model.StaticEntity","k":"def","x":""},
{"l":"io/github/srs/model/StaticEntity$.html#obstacle-6cd","e":false,"i":"","n":"obstacle","t":"obstacle(pos: Point2D, orient: Orientation, width: Int, height: Int): Validation[StaticEntity]","d":"io.github.srs.model.StaticEntity","k":"def","x":""},
{"l":"io/github/srs/view.html#","e":false,"i":"","n":"io.github.srs.view","t":"io.github.srs.view","d":"","k":"package","x":""},
{"l":"io/github/srs/view/SimpleView.html#","e":false,"i":"","n":"SimpleView","t":"SimpleView","d":"io.github.srs.view","k":"class","x":""},
{"l":"io/github/srs/view/SimpleView.html#close-94c","e":false,"i":"","n":"close","t":"close(): Unit","d":"io.github.srs.view.SimpleView","k":"def","x":""},
{"l":"io/github/srs/view/SimpleView.html#init-94c","e":false,"i":"","n":"init","t":"init(): Unit","d":"io.github.srs.view.SimpleView","k":"def","x":""},
{"l":"io/github/srs/view/SimpleView.html#plotData-fffff3b3","e":false,"i":"","n":"plotData","t":"plotData(data: Int): Unit","d":"io.github.srs.view.SimpleView","k":"def","x":""},
{"l":"io/github/srs/view/ViewModule$.html#","e":false,"i":"","n":"ViewModule","t":"ViewModule","d":"io.github.srs.view","k":"object","x":""},
{"l":"io/github/srs/view/ViewModule$.html#Requirements-0","e":false,"i":"","n":"Requirements","t":"Requirements = Provider","d":"io.github.srs.view.ViewModule","k":"type","x":""},
{"l":"io/github/srs/view/ViewModule$$Component.html#","e":false,"i":"","n":"Component","t":"Component","d":"io.github.srs.view.ViewModule","k":"trait","x":""},
{"l":"io/github/srs/view/ViewModule$$Component$View$.html#","e":false,"i":"","n":"View","t":"View","d":"io.github.srs.view.ViewModule.Component","k":"object","x":""},
{"l":"io/github/srs/view/ViewModule$$Component$View$.html#apply-fffff44c","e":false,"i":"","n":"apply","t":"apply(): View","d":"io.github.srs.view.ViewModule.Component.View","k":"def","x":""},
{"l":"io/github/srs/view/ViewModule$$Interface.html#","e":false,"i":"","n":"Interface","t":"Interface extends Provider, Component","d":"io.github.srs.view.ViewModule","k":"trait","x":""},
{"l":"io/github/srs/view/ViewModule$$Provider.html#","e":false,"i":"","n":"Provider","t":"Provider","d":"io.github.srs.view.ViewModule","k":"trait","x":""},
{"l":"io/github/srs/view/ViewModule$$Provider.html#view-0","e":false,"i":"","n":"view","t":"view: View","d":"io.github.srs.view.ViewModule.Provider","k":"val","x":""},
{"l":"io/github/srs/view/ViewModule$$View.html#","e":false,"i":"","n":"View","t":"View","d":"io.github.srs.view.ViewModule","k":"trait","x":""},
{"l":"io/github/srs/view/ViewModule$$View.html#init-94c","e":false,"i":"","n":"init","t":"init(): Unit","d":"io.github.srs.view.ViewModule.View","k":"def","x":""},
{"l":"io/github/srs/view/ViewModule$$View.html#plotData-fffff3b3","e":false,"i":"","n":"plotData","t":"plotData(data: Int): Unit","d":"io.github.srs.view.ViewModule.View","k":"def","x":""},
{"l":"io/github/srs/Launcher$.html#","e":false,"i":"","n":"Launcher","t":"Launcher extends Interface, Interface, Interface","d":"io.github.srs","k":"object","x":""},
{"l":"io/github/srs/Launcher$.html#controller-0","e":false,"i":"","n":"controller","t":"controller: Controller","d":"io.github.srs.Launcher","k":"val","x":""},
{"l":"io/github/srs/Launcher$.html#model-0","e":false,"i":"","n":"model","t":"model: Model","d":"io.github.srs.Launcher","k":"val","x":""},
{"l":"io/github/srs/Launcher$.html#run-94c","e":false,"i":"","n":"run","t":"run(): Unit","d":"io.github.srs.Launcher","k":"def","x":""},
{"l":"io/github/srs/Launcher$.html#view-0","e":false,"i":"","n":"view","t":"view: View","d":"io.github.srs.Launcher","k":"val","x":""},
{"l":"io/github/srs/run.html#","e":false,"i":"","n":"run","t":"run","d":"io.github.srs","k":"class","x":""}];