# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ping.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'ping.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nping.proto\x12\x14io.github.srs.protos\"\x18\n\x08PingPong\x12\x0c\n\x04\x66rom\x18\x01 \x01(\t\"\'\n\x0bPingPongAck\x12\x0c\n\x04\x66rom\x18\x01 \x01(\t\x12\n\n\x02to\x18\x02 \x01(\t2Y\n\x06Ponger\x12O\n\x04Ping\x12\x1e.io.github.srs.protos.PingPong\x1a!.io.github.srs.protos.PingPongAck\"\x00(\x01\x30\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ping_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PINGPONG']._serialized_start=36
  _globals['_PINGPONG']._serialized_end=60
  _globals['_PINGPONGACK']._serialized_start=62
  _globals['_PINGPONGACK']._serialized_end=101
  _globals['_PONGER']._serialized_start=103
  _globals['_PONGER']._serialized_end=192
# @@protoc_insertion_point(module_scope)
